spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/norpac-mysql?useLegacyDatetimeCode=false&serverTimezone=UTC&autoReconnect=true&failOverReadOnly=false&maxReconnects=10&useSSL=false&sessionVariables=sql_mode=''&useUnicode=true&characterEncoding=utf8   
    username: root 
    password: password

tenant: 
  name: norpac-mysql
